//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalReportsNinja.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SQL_Use_IntegratedSecurity {
            get {
                return ((bool)(this["SQL_Use_IntegratedSecurity"]));
            }
            set {
                this["SQL_Use_IntegratedSecurity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableLogToConsole {
            get {
                return ((bool)(this["EnableLogToConsole"]));
            }
            set {
                this["EnableLogToConsole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Smtp.office365.com")]
        public string SMTP_Server_Address {
            get {
                return ((string)(this["SMTP_Server_Address"]));
            }
            set {
                this["SMTP_Server_Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("587")]
        public int SMTP_Server_Port {
            get {
                return ((int)(this["SMTP_Server_Port"]));
            }
            set {
                this["SMTP_Server_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SMTP_SSL_Reqruired {
            get {
                return ((bool)(this["SMTP_SSL_Reqruired"]));
            }
            set {
                this["SMTP_SSL_Reqruired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SMTP_Authentication_Used {
            get {
                return ((bool)(this["SMTP_Authentication_Used"]));
            }
            set {
                this["SMTP_Authentication_Used"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NA")]
        public string Email_CC {
            get {
                return ((string)(this["Email_CC"]));
            }
            set {
                this["Email_CC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NA")]
        public string Email_BCC {
            get {
                return ((string)(this["Email_BCC"]));
            }
            set {
                this["Email_BCC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"The information contained is intended for the named recipients only, it may contain confidential and/or legally privileged information and is only intended for the use of the person to whom it is addressed. If you have received this e-mail in error you must not copy, duplicate, forward, print or distribute any information contained herein, but must ensure that this e-mail is permanently deleted and advise the sender. ")]
        public string Email_Message_Body {
            get {
                return ((string)(this["Email_Message_Body"]));
            }
            set {
                this["Email_Message_Body"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Keep_Outputfile_after_Sending {
            get {
                return ((bool)(this["Keep_Outputfile_after_Sending"]));
            }
            set {
                this["Keep_Outputfile_after_Sending"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Default_Printer_Name {
            get {
                return ((string)(this["Default_Printer_Name"]));
            }
            set {
                this["Default_Printer_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SQLSERVERNAME")]
        public string SQL_Server_Name {
            get {
                return ((string)(this["SQL_Server_Name"]));
            }
            set {
                this["SQL_Server_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SQLDBNAME")]
        public string SQL_Database_Name {
            get {
                return ((string)(this["SQL_Database_Name"]));
            }
            set {
                this["SQL_Database_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("REPORTUSERNAME")]
        public string SQL_User_Name {
            get {
                return ((string)(this["SQL_User_Name"]));
            }
            set {
                this["SQL_User_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("REPORTUSERPASSWORD")]
        public string SQL_Password {
            get {
                return ((string)(this["SQL_Password"]));
            }
            set {
                this["SQL_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("USERNAME")]
        public string SMTP_User_Name {
            get {
                return ((string)(this["SMTP_User_Name"]));
            }
            set {
                this["SMTP_User_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PASSWORD")]
        public string SMTP_Password {
            get {
                return ((string)(this["SMTP_Password"]));
            }
            set {
                this["SMTP_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("noreply@noreply.com")]
        public string Email_From {
            get {
                return ((string)(this["Email_From"]));
            }
            set {
                this["Email_From"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NoReply")]
        public string Email_From_Display_Name {
            get {
                return ((string)(this["Email_From_Display_Name"]));
            }
            set {
                this["Email_From_Display_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Automated Crystal Reports")]
        public string Email_Subject {
            get {
                return ((string)(this["Email_Subject"]));
            }
            set {
                this["Email_Subject"] = value;
            }
        }
    }
}
